[project]
name = "LicenseGuard-agent"
version = "0.1.0"
description = "An AI agent responsible for providing insights to the frontend"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
